---
#DNS and NTP data
servers:
 - DNS1: "DNS1"
   IP: 192.168.10.16
   
 - DNS2: "DNS2"
   IP: 192.168.10.1

 - DNS3: "DNS3"
   IP: 8.8.8.8
   
#Vlans in LAB network
vlans:
  - id: 10
    name: "user_vlan-10"
    present: True
  - id: 20
    name: "dev_vlan-20"
    present: True
  - id: 30
    name: "accounting_vlan-30"
    present: True
  - id: 100
    name: "mgmt_vlan-100"
    present: True
  - id: 999
    name: "native_vlan-999"
    present: True

#Trusted source networks for VTY-Sec ACL
LAN_net: 192.168.10.0 0.0.0.31
LAB_net: 10.10.210.0 0.0.0.255
MGMT_net: 172.16.1.0 0.0.0.255

domain_name: lab

#Routing protocols
#ospf:
# - process_id: "1"
# - area: "1"