<<<<<<< HEAD
---
#DNS and NTP data
servers:
 - DNS1: "DNS1"
   IP: 8.8.8.8
   
 - DNS2: "DNS2"
   IP: 1.1.1.1

 - DNS3: "DNS3"
   IP: 4.4.2.2

 - DNS4: "DNS4"
   IP: 8.8.1.1
   
#Vlans in LAB network
vlans:
  - id: 10
    name: "Access"
    state: present
  - id: 20
    name: "Finance"
    state: absent
  - id: 30
    name: "IT_VLAN"
    state: present
  - id: 40
    name: "Developers"
    state: present
  - id: 50
    name: "Executives"
    state: absent
  - id: 60
    name: "Accounting"
    state: absent
  - id: 70
    name: "Native_vlan"
    state: present
  - id: 100
    name: "LAB_vlan"
    state: present

#Trusted source networks for VTY-Sec ACL
LAN_net: 192.168.10.0 0.0.0.31
LAB_net: 10.10.210.0 0.0.0.255

domain_name: lab.local
=======
---
#DNS and NTP data
servers:
 - DNS1: "DNS1"
   IP: 192.168.10.16
   
 - DNS2: "DNS2"
   IP: 192.168.10.1

 - DNS3: "DNS3"
   IP: 8.8.8.8
   
#Vlans in LAB network
vlans:
  - id: 10
    name: "user_vlan-10"
  - id: 20
    name: "dev_vlan-20"
  - id: 30
    name: "accounting_vlan-30"
  - id: 100
    name: "mgmt_vlan-100"
  - id: 999
    name: "native_vlan-999"

#Trusted source networks for VTY-Sec ACL
LAN_net: 192.168.10.0 0.0.0.31
LAB_net: 10.10.210.0 0.0.0.255
MGMT_net: 172.16.1.0 0.0.0.255

domain_name: lab

#Routing protocols
ospf_mgmt:
  process_id: 1
  area: 1
>>>>>>> interface_template
