---
#DNS and NTP data
servers:
  DNS1: 8.8.8.8
  DNS2: 1.1.1.1
  DNS3: 4.4.2.2
  DNS4: 8.8.1.1

domain_name: lab.local

#Vlans in LAB network
vlans:
  - id: 10
    name: "HR_VLAN"
  - id: 20
    name: "Finance"
  - id: 30
    name: "IT_VLAN"
  - id: 40
    name: "Developers"
  - id: 50
    name: "Executives"
  - id: 60
    name: "Accounting"
  - id: 70
    name: "Native_vlan"
  - id: 100
    name: "LAB_vlan"

#Trusted source networks for VTY-Sec ACL
LAN_net: 192.168.10.0 0.0.0.31
LAB_net: 10.10.210.0 0.0.0.255