---
#DNS and NTP data
GOOGLE: 8.8.8.8
CLOUD: 1.1.1.1
domain_name: coffeenet.local

#Vlans in LAB network
vlans:
  - id: 10
    name: "HR_VLAN"
  - id: 20
    name: "FINANCE_VLAN"
  - id: 30
    name: "IT_VLAN"
  - id: 40
    name: "Developers"
  - id: 50
    name: "Executives"
  - id: 60
    name: "Accounting"
  - id: 70
    name: "Native_vlan"
  - id: 5000
    name: "Test for failure"