---
- name: Create/enforce VTY-Sec ACL and apply to the VTY lines

  gather_facts: no

  vars_prompt:
    - name: hosts 
      prompt: "Which group should we run the playbook against?"
      private: no
      default: LAB
    - name: "ansible_user"
      prompt: "Enter your username"
      private: no
    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: "{{hosts}}"


  tasks:

    - name: Include group vars
      include_vars:
       file: "/etc/ansible/Playbooks/host_vars/{{hosts}}/{{inventory_hostname}}.yaml"

    - name: Enforce VTY-Sec ACL configuration
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
              - name: VTY-Sec
                acl_type: standard
                aces:
                  - grant: permit
                    sequence: 10
                    source:
                      address: 10.10.1.0
                      wildcard_bits: 0.0.0.255   
                  - grant: permit
                    sequence: 20
                    source:
                      address: 10.10.80.0
                      wildcard_bits: 0.0.0.255
                  - grant: permit
                    sequence: 30
                    source: 
                      address: 10.10.10.0
                      wildcard_bits: 0.0.0.255
                  - grant: permit
                    sequence: 40
                    source: 
                      address: 10.10.11.0
                      wildcard_bits: 0.0.0.255
                  - grant: permit
                    sequence: 50
                    source: 
                      address: 10.10.22.0
                      wildcard_bits: 0.0.0.255
                  - grant: permit
                    sequence: 60
                    source: 
                      address: 10.10.23.0
                      wildcard_bits: 0.0.0.255
                  - grant: permit
                    sequence: 70
                    source: 
                      address: 10.10.35.64
                      wildcard_bits: 0.0.0.31
                  - grant: permit
                    sequence: 80
                    source: 
                      address: 10.10.35.96
                      wildcard_bits: 0.0.0.31
                  - grant: permit
                    sequence: 90
                    source: 
                      address: 10.10.44.0
                      wildcard_bits: 0.0.0.63
                  - grant: permit
                    sequence: 100
                    source: 
                      address: 10.10.45.0
                      wildcard_bits: 0.0.0.255
                  - grant: permit
                    sequence: 110
                    source: 
                      address: 10.10.104.0
                      wildcard_bits: 0.0.0.255
                  - grant: permit
                    sequence: 120
                    source: 
                      address: 10.10.108.0
                      wildcard_bits: 0.0.0.255
                  - grant: permit
                    sequence: 130
                    source: 
                      address: 10.10.58.16 
                      wildcard_bits: 0.0.0.15
                  - grant: permit
                    sequence: 140
                    source: 
                      address: "{{ ACL_local_LAN }}"
                      wildcard_bits: 0.0.0.255
                  - grant: deny
                    sequence: 150
                    source: 
                      any: true
        state: replaced 

    - name: Apply ACL to VTY lines
      cisco.ios.ios_config:
        lines:
          - line vty 0 15
          - access-class VTY-Sec in