---
- name: Change LFN standard DNS servers on switching infrastructure

  hosts: switches

  gather_facts: no

  tasks:

   - name: Include host-specific variables
     include_vars:
       file: "group_vars/config_pillars.yaml"

   - name: Configure standard LFN DNS servers on spoke site switches
     cisco.ios.ios_system:
      name_servers:
       - "{{ Google }}" 
       - "{{ Trip1 }}"
     
   - name: Save running to startup if the playbook made a change
     cisco.ios.ios_config:
      save_when: changed