---
- name: Configures the DNS server, hostname and saves the configuration if changes were made

  hosts: switches

  gather_facts: no

  tasks:

   - name: Include group variables
     include_vars:
       file: "group_vars/config_pillars.yaml"

   - name: Configure Google and Cloudflare DNS servers on hosts
     cisco.ios.ios_system:
      name_servers:
       - "{{ GOOGLE }}" 
       - "{{ CLOUD }}"

   - name: Enforce the hostname from the host_vars file
     cisco.ios.ios_config: 
       lines: hostname {{ hostname }}
     
   - name: Save running to startup if the playbook made a change
     cisco.ios.ios_config:
      save_when: changed