---
- name: Pulls the hostname and http configuration and places the output in /Playbook Outputs/httpconfig.txt. 

  gather_facts: yes

  vars_prompt:
    - name: hosts 
      prompt: "Which group should we run the playbook against?"
      private: no
      default: LAB
    - name: "ansible_user"
      prompt: "Enter your username"
      private: no
    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: "{{hosts}}"

  tasks:

   - name: Execute show command and store output in 'output' variable.
     cisco.ios.ios_command:
      commands:
        - show ip http server status
     register: output

   - name: Searches in the var 'output' http config and only registers output statuses that are enabled with var 'http_server_status'.
     set_fact:
       http_server_status: "{{ output.stdout_lines | select('search', 'HTTP server status: Disabled') | list }}"

     #Debugs 'second_line' var to the terminal.
#   - debug:
#       var: http_server_status

   - name: Prints the switch hostname and 'http_server_status' var to a local file. 
     local_action:
       module: lineinfile
       dest: "/etc/ansible/Playbook Outputs/httpconfig.txt"
       create: yes
       line: "Hostname: {{ inventory_hostname }} | HTTP Config: {{ http_server_status | list | first }}\n"