---
- name: Get IOS version

  hosts: switches

  gather_facts: yes
  
#  vars_prompt:
#    - name: "ansible_user"
#      prompt: "Enter the username"
#      private: no
#    - name: "ansible_password"
#      prompt: "Enter the password"
#      private: yes

  tasks:

    - name: Gather the hostname, hardware platform, ios, and send them to a local .txt file for review
      local_action:
        module: lineinfile
        dest: "../Playbook Outputs/IOS_version_inventory.txt"
        create: yes
        line: "Hostname:{{ inventory_hostname }} Platform:{{ ansible_facts['net_model'] }} IOS Version:{{ ansible_net_version }}\n"