---
- name: Create/ enforce VTY-Sec ACL and apply to the VTY lines

  hosts: switches

  gather_facts: no

  tasks:

    - name: Enforce VTY-Sec ACL configuration
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
              - name: VTY-Sec
                acl_type: standard
                aces:
                  - grant: permit
                    sequence: 10
                    source:
                      address: "{{ ACL_LAN_Network }}"
                      wildcard_bits: "{{ ACL_LAN_wildcard_mask }}"
                  - grant: permit
                    sequence: 20
                    source: 
                      address: "{{ ACL_LAB_Network }}"
                      wildcard_bits: "{{ ACL_LAB_wildcard_mask }}"
                  - grant: deny
                    sequence: 30
                    source:
                      any: true                      
        state: replaced