---
- name: Rollback configuration if errors

  gather_facts: no

  vars_prompt:
    - name: hosts 
      prompt: "Which group should we run the playbook against?"
      private: no
      default: LAB
    - name: "ansible_user"
      prompt: "Enter your username"
      private: no
    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: "{{hosts}}"

  tasks:
    - name: Read the saved running config
      slurp:
        src: "/etc/ansible/Playbooks/host_vars/{{ hosts }}/{{ inventory_hostname }}.cfg"
      register: backup_config

    - name: Write the backup config to the device
      ios_config:
        lines: "{{ backup_config.content | b64decode | ('\n') }}"
