---
- name: Standard SW Provisioning playbook

  gather_facts: no

  vars_prompt:
    - name: hosts 
      prompt: "Which group should we run the playbook against?"
      private: no
      default: LAB
    - name: "ansible_user"
      prompt: "Enter your username"
      private: no
    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: "{{hosts}}"

  tasks:

   - name: Include host-specific variables
     include_vars:
       file: "/etc/ansible/Playbooks/host_vars/{{ hosts }}/{{ inventory_hostname }}.yaml"

   - name: Render a Jinja2 template onto an IOSxe device
     cisco.ios.ios_config:
       src: config_templates/IOSxe_config.j2
       match: line
       backup: false
       backup_options:
         dir_path: ./etc/ansible/Config Backups/