---
- name: Gets the locally configured accounts stored for record and then changes the passwords

  gather_facts: no

  vars_prompt:
    - name: hosts 
      prompt: "Which group should we run the playbook against?"
      private: no
      default: LAB
    - name: "ansible_user"
      prompt: "Enter your username"
      private: no
    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: "{{hosts}}"

  tasks:

   - name: Registers the below command with the variable name_server_output
     cisco.ios.command:
      commands:
        - show run | sec user
     register: user_account
     
   - name: Get only the standard output in position zero of the output
     set_fact:
       second_line: "{{ user_account.stdout_lines[0] }}"

   - name: Generate a new 16 character ascii password
     set_fact:
       new_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters+digits!@#$%&') }}"

   - name: Change the password of the local admin accounts
     cisco.ios.ios_user:
      name: #REDACTED#
      configured_password: "{{new_password}}"
      password_type: secret
      update_password: always
      state: present

   - name: Update the ansible_password for all switches in the hosts.ini file
     ansible.builtin.ini_file:
        path: "/etc/ansible/hosts"
        section: "{{inventory_hostname}}:vars"
        option: "ansible_password"
        value: "{{new_password}}"

   - name: Save the user account configuration to a local .txt file
     local_action:
       module: lineinfile
       dest: "/etc/ansible/Playbook Outputs/localuserconfig.txt"
       create: yes
       line: "{{ inventory_hostname }}\n {{ second_line }}\n"
   
   - name: Save the newly configured password to a local .txt file as another precautionary measure
     local_action:
       module: lineinfile
       dest: "/etc/ansible/Playbooks/host_vars/spoke_switches/{{inventory_hostname}}.yaml"
       create: yes
       line: "{{inventory_hostname}} new net.admin password is: {{new_password}}\n"
       