---
- name: Executes a test ping against an IP and prints output to terminal

  gather_facts: no

  vars_prompt:
    - name: hosts 
      prompt: "Which group should we run the playbook against?"
      private: no
      default: LAB
    - name: "ansible_user"
      prompt: "Enter your username"
      private: no
    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes
    - name: "dest"
      prompt: "Please enter the IP address you'd like to test"
      private: no

  hosts: "{{hosts}}"

  tasks:

   - name: Test reachability to dest IP using default vrf
     cisco.ios.ios_ping:
      dest: "{{dest}}"