---
- name: Pulls a full backup of running-config

  gather_facts: no

  vars_prompt:
    - name: "ansible_user"
      prompt: "Enter your username"
      private: no

    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: "{{hosts}}"

  tasks:

   - name: Take a backup of the running configuration from hosts and stores in local directory
     cisco.ios.ios_config:
      backup: true
      backup_options:
        dir_path: /etc/ansible/config_backups/

   - name: Save running to startup
     cisco.ios.ios_config:
      save_when: always
