---
- name: Enforce a config as code by utilizing a j2 template and importing variables

  gather_facts: no

  vars_prompt:
    - name: "ansible_user"
      prompt: "Enter your username"
      private: no

    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: all

  tasks:

    - name: Include PROD production host variable files
      include_vars:
        file: "/etc/ansible/Playbooks/host_vars/production/{{inventory_hostname}}.yaml"
      when: "'PROD' in group_names"

    - name: Include DEV development host variable files
      include_vars:
        file: "/etc/ansible/Playbooks/host_vars/development/{{inventory_hostname}}.yaml"
      when: "'DEV' in group_names"

    - name: Include group variable files
      include_vars:
        file: "/etc/ansible/Playbooks/group_vars/all.yaml"

    - name: Render Jinja2 template unto SWITCHES
      cisco.ios.ios_config:
        src: /etc/ansible/config_templates/ios_switch.j2
        match: exact
      when: "'SWITCHES' in group_names"

    - name: Render Jinja2 template unto DEV-SWITCHES 
      cisco.ios.ios_config:
        src: /etc/ansible/config_templates/ios_switch.j2
        match: exact
      when: "'DEV-SWITCHES' in group_names"

    - name: Save running configuration to startup
      cisco.ios.ios_config:
        save_when: always
        
    - name: Check the running-config of the devices in the switches group in the hosts inventory file against the master
      cisco.ios.ios_config:
        diff_against: intended
        intended_config: "/etc/ansible/ios_switch.j2"
      when: "'SWITCHES' in group_names"

  diff: true