---
- name: Renders a Jinja2 template to IOS devices

  gather_facts: no

  vars_prompt:
    - name: hosts
      prompt: "Which group should we run the playbook against?"
      private: no
      default: LAB

    - name: "ansible_user"
      prompt: "Enter your username"
      private: no

    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: "{{hosts}}"

  tasks:

    - name: Render a Jinja2 template onto lab devices
      cisco.ios.ios_config:
        backup: true
      src: /etc/ansible/config_templates/ios_j2_template.yaml
