---
- name: Enforce a config as code by utilizing a j2 template and importing variables

  gather_facts: no

  vars_prompt:
    - name: hosts
      prompt: "Which group should we run the playbook against?"
      private: no
      default: LAB

    - name: "ansible_user"
      prompt: "Enter your username"
      private: no

    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: "{{hosts}}"

  tasks:

    - name: Include host variable files.
      include_vars:
        prod: "/etc/ansible/Playbooks/host_vars/production{{ inventory_hostname }}.yaml"
      when: "'PROD' in group_names"

    - name: Include host variable files.
      include_vars:
        prod: "/etc/ansible/Playbooks/host_vars/development{{ inventory_hostname }}.yaml"
      when: "'DEV' in group_names"
        

        

    - name: Include group variable files.
      include_vars:
        file: "/etc/ansible/Playbooks/group_vars/all.yaml"


    - name: Renders the jinja2 template onto IOS devices
      cisco.ios.ios_config:
        src: /etc/ansible/config_templates/ios_switch.j2
        match: exact

    - name: Save running configuration to startup
      cisco.ios.ios_config:
        save_when: always
        
    - name: Check the running-config against master config
      cisco.ios.ios_config:
        diff_against: intended
        intended_config: "/etc/ansible/ios_j2_template.j2s"

  diff: true