---
- name: Test authenticate to device to validate authentication and authorization 

  gather_facts: no

  vars_prompt:
    - name: "ansible_user"
      prompt: "Enter your username"
      private: no
      
    - name: "ansible_password"
      prompt: "Enter your password"
      private: yes

  hosts: all

  tasks:

   - name: Enter priv exec mode
     cisco.ios.command:
      commands:
        - config t
        - do show run
     when: "'SWITCHES' in group_names"

   - name: Enter priv exec mode
     cisco.ios.command:
      commands:
        - config t
        - do show run
     when: "'DEV-SWITCHES' in group_names"