---
- name: Applies VTY-Sec standard ACL inward on vty line 0-15

  hosts: switches

  gather_facts: no

  tasks:


   - name: Apply ACL to VTY lines
     cisco.ios.ios_config:
       lines:
        - access-class VTY-Sec in
       parents: line vty 0 15